import styles from "./restaurant.module.css"
import Image from "next/image";


export const restaurantImages = [
    { src: '/photos/restaurant1.png',
      alt: 'Photo 1',
      original:'photos/MainRestaurant/restaurant1.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant1.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant2.png',
      alt: 'Photo 2',
      original:'photos/MainRestaurant/restaurant2.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant2.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant3.png',
      alt: 'Photo 3',
      original:'photos/MainRestaurant/restaurant3.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant3.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant4.png',
      alt: 'Photo 4',
      original:'photos/MainRestaurant/restaurant4.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant4.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant5.png',
      alt: 'Photo 5',
      original:'photos/MainRestaurant/restaurant5.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant5.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant6.png',
      alt: 'Photo 6',
      original:'photos/MainRestaurant/restaurant6.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant6.jpg',
      width: 6000,
      height: 4000,
    },
  ];

  export const restaurantDescription = 'Ресторан сочетает в себе современный стиль и уют. Просторный зал с комфортной мебелью, мягким освещением и тщательно подобранными элементами интерьера. Здесь можно насладиться не только вкусной едой, приготовленной из свежих ингредиентов, но\u00A0и\u00A0атмосферой тепла, гостеприимства и\u00A0заботы.'
  