export const restaurantImages = [
    { src: '/photos/restaurant1.png',
      alt: 'Ресторан парк-отеля Дзуарикау — интерьер зала',
      original:'photos/MainRestaurant/restaurant1.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant1.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant2.png',
      alt: 'Ресторан парк-отеля Дзуарикау — обеденная зона',
      original:'photos/MainRestaurant/restaurant2.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant2.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant3.png',
      alt: 'Ресторан парк-отеля Дзуарикау — сервировка стола',
      original:'photos/MainRestaurant/restaurant3.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant3.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant4.png',
      alt: 'Ресторан парк-отеля Дзуарикау — блюда кавказской кухни',
      original:'photos/MainRestaurant/restaurant4.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant4.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant5.png',
      alt: 'Ресторан парк-отеля Дзуарикау — уютная атмосфера',
      original:'photos/MainRestaurant/restaurant5.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant5.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/restaurant6.png',
      alt: 'Ресторан парк-отеля Дзуарикау — зал для гостей',
      original:'photos/MainRestaurant/restaurant6.jpg',
      thumbnail: 'photos/MainRestaurant/restaurant6.jpg',
      width: 6000,
      height: 4000,
    },
  ];

  export const restaurantDescription = 'Ресторан сочетает в себе современный стиль и\u00A0уют. Просторный зал с комфортной мебелью, мягким освещением и тщательно подобранными элементами интерьера. Здесь можно насладиться не только вкусной едой, приготовленной из\u00A0свежих ингредиентов, но\u00A0и\u00A0атмосферой тепла, гостеприимства и\u00A0заботы.'
