export const aboutImages = [
    { src: '/photos/about1.png',
      alt: 'Photo 1',
      original:'photos/MainPage/about1.jpg',
      thumbnail: 'photos/MainPage/about1.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/about2.png',
      alt: 'Photo 2',
      original:'photos/MainPage/about2.jpg',
      thumbnail: 'photos/MainPage/about2.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/about3.png',
      alt: 'Photo 3',
      original:'photos/MainPage/about3.jpg',
      thumbnail: 'photos/MainPage/about3.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/about4.png',
      alt: 'Photo 4',
      original:'photos/MainPage/about4.jpg',
      thumbnail: 'photos/MainPage/about4.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/about5.png',
      alt: 'Photo 5',
      original:'photos/MainPage/about5.jpg',
      thumbnail: 'photos/MainPage/about5.jpg',
      width: 6000,
      height: 4000,
    },
    { src: '/photos/about6.png',
      alt: 'Photo 6',
      original:'photos/MainPage/about6.jpg',
      thumbnail: 'photos/MainPage/about6.jpg',
      width: 6000,
      height: 4000,
    },
  ];

export const aboutDescription = 'Парк-отель «Дзуарикау» расположен в живописном уголке Осетии, недалеко от\u00A0Владикавказа и\u00A0вблизи живописного поселка Фиагдон. Это идеальное место для отдыха на\u00A0природе — в\u00A0тишине, среди гор и\u00A0чистого воздуха. Уютные номера, гостеприимная атмосфера и\u00A0красота окружающих пейзажей сделают ваш отдых по-настоящему особенным.'
export const mobileAboutDescriptionPartOne = 'Парк-отель «Дзуарикау» расположен в\u00A0живописном уголке Осетии, недалеко от\u00A0Владикавказа и\u00A0вблизи живописного поселка Фиагдон.'
export const mobileAboutDescriptionPartTwo = 'Это идеальное место для отдыха на природе — в\u00A0тишине, среди гор и\u00A0чистого воздуха. Уютные номера, гостеприимная атмосфера и\u00A0красота окружающих пейзажей сделают ваш отдых по-настоящему особенным.'

